INSERT INTO eolida.area (id,area) VALUES
	 (1,'Rentas'),
	 (2,'Obras Sanitarias'),
	 (3,'Seccion Transito'),
	 (4,'Cajas'),
	 (5,'Tesoreria'),
	 (6,'Desarrollo'),
	 (7,'Contaduria'),
	 (8,'Suministros'),
	 (9,'Direccion de Desarrollo Humano'),
	 (10,'OySP'),
	 (11,'Infracciones'),
	 (12,'Area Legal y Técnica'),
	 (13,'Expedicion de Licencia de Conducir'),
	 (14,'Secretaria de Economia y Hacienda'),
	 (15,'Secretaria de Gobierno'),
	 (16,'Centro Salustiano Minguillon'),
	 (17,'Prevencion y Promocion de la Salud'),
	 (18,'Area de Inclusión de Personas con Discapacidad'),
	 (19,'Area de la Juventud'),
	 (20,'Subdireccion de Deportes'),
	 (21,'Deporte Social y Recreativo'),
	 (22,'Deporte Federado'),
	 (23,'Direccion de Prevención y Seguridad Urbana'),
	 (24,'DESPACHO'),
	 (25,'Mesa de Entrada'),
	 (26,'Archivo'),
	 (27,'Bromatologia'),
	 (28,'Subdireccion de Recursos Humanos'),
	 (29,'Subdireccion de Catastro'),
	 (30,'Almacenes'),
	 (31,'Inventario y Archivo'),
	 (32,'Informatica y Redes'),
	 (33,'Comunicaciones'),
	 (34,'Subsecretaria de Integracion y Participacion Ciudadana'),
	 (35,'Subdireccion de Cultura y Educación'),
	 (36,'Imefaa'),
	 (37,'Sala Eva Peron'),
	 (38,'Salon Municipal'),
	 (39,'Museo Municipal'),
	 (40,'Centro de Apoyo Tecnologico'),
	 (41,'Relaciones con la Comunidad'),
	 (42,'Informacion de Gestion Publica y Protocolo'),
	 (43,'Area Industrial'),
	 (44,'Microemprendimientos'),
	 (45,'Turismo'),
	 (46,'Secretaria de Planeamiento, Obras e Infraestructura'),
	 (47,'Departamento de Desarrllo Urbano y Formulacion de Proyectos'),
	 (48,'Equipo de Proyectos'),
	 (49,'Unidad de Gestion e Inspeccion de Obras'),
	 (50,'Inspectores'),
	 (51,'Directores de Obras'),
	 (52,'Departamento de Construccion y Mantenimiento de Dependencias Municipales'),
	 (53,'Unidad de Albañileria y Pintura'),
	 (54,'Unidad de Electromecanica'),
	 (55,'Unidad de Plomeria y Gas'),
	 (56,'Unidad de Telefonia'),
	 (57,'Servicios Generales'),
	 (58,'Unidad de Abastecimiento'),
	 (59,'Direccion de Infraestructura y Equipamiento Urbano'),
	 (60,'Unidad de Maquinistas'),
	 (61,'Unidad de Albañileria Urbana'),
	 (62,'Unidad de Pintura Urbana'),
	 (63,'Alumbrado Publico'),
	 (64,'Unidad de Pavimentacion'),
	 (65,'Unidad de Extension de Redes de Obras Sanitarias'),
	 (66,'Parques y Paseos'),
	 (67,'Secretaria de Desarrollo Urbano y Ambiente'),
	 (68,'Servicios de Higiene Urbana'),
	 (69,'Atencion Ciudadana'),
	 (70,'Taller de Mantenimiento'),
	 (71,'Servicios Administrativos'),
	 (72,'Medio Ambiente'),
	 (73,'Administración Fiscal y Tributaria'),
	 (74,'Presidencia Municipal'),
	 (75,'Cloacas Obras y Servicios'),
	 (76,'Honorable Concejo Deliberante'),
	 (78,'Obrador San Jose'),
	 (79,'Taller de Herreria'),
	 (80,'Planta de Reciclado'),
	 (81,'Habilitaciones'),
	 (82,'Servicio de Cobranza Administrativa y Judiciales'),
	 (83,'Externa'),
	 (84,'Centro de Ayuda al Niño'),
	 (85,'Choferes'),
	 (86,'Oficina Municipal de Informacion al Consumidor'),
	 (87,'Juzgado de Faltas'),
	 (88,'Correo Interno'),
	 (89,'Seguros'),
	 (90,'Secretaría del Ejecutivo Municipal'),
	 (91,'Escuela de Musica'),
	 (92,'Area Niñez, Adolescencia y Familia (NAF)'),
	 (93,'Limpieza'),
	 (94,'Hogar Nuevo Amanecer'),
	 (95,'Consejo de Adultos Mayores y Hogar De Dia'),
	 (96,'Subsecretaria de Innovacion Social y Participacion Ciudadana'),
	 (97,'Prensa y Comunicacion'),
	 (98,'Direccion de Planeamiento y Obras Privadas'),
	 (99,'Area de Salud'),
	 (100,'Area de Salud Animal'),
	 (101,'Observatorio de Violencia'),
	 (102,'Area de Programacion Artistica y Comunitaria'),
	 (103,'Comunicaciones'),
	 (104,'Dirección de Hacienda y Presupuesto'),
	 (105,'Subsecretaria de Servicios Publicos'),
	 (106,'Mantenimiento Vial'),
	 (107,'Consejo Consultivo de Politicas Agropecuarias'),
	 (108,'Agencia de Desarrollo Local'),
	 (109,'Protocolo y Ceremonial'),
	 (110,'Servicio de Mantenimiento'),
	 (111,'Academia de Corte y Confeccion'),
	 (112,'Centro Cultural La Estacion'),
	 (113,'Coro Municipal del Centenario'),
	 (114,'Coro de Adultos Mayores Sueño del Alma '),
	 (115,'Ciclo Cultivarte'),
	 (116,'Estadistica'),
	 (117,'NIDO'),
	 (118,'Area de Educacion y Capacitacion Laboral'),
	 (119,'Sub Direccion de Empleo y Emprendurismo'),
	 (120,'Area Articulacion Campo-Ciudad'),
	 (121,'Defensa Civil'),
	 (122,'Jardin Barrilete de Sueños (Barrio San Miguel)'),
	 (123,'Ambiente');