INSERT INTO eolida.tipo_reclamo (id,tipo) VALUES
	 (1,'PERDIDA DE AGUA'),
	 (2,'CLOACAS'),
	 (3,'BAJA PRESION RED AGUA POTABLE'),
	 (4,'CAÑERIA PRINCIPAL ROTA'),
	 (5,'AGUA DE RED NO POTABLE'),
	 (6,'RECOLECCION DE RESIDUOS'),
	 (7,'LIMPIEZA Y RESIDUOS'),
	 (8,'INTIMACION DE TERRENOS'),
	 (9,'LIMPIEZA DE TERRENOS PARTICULARES'),
	 (10,'CORTE PASTO EN LA VIA PUBLICA');
INSERT INTO eolida.tipo_reclamo (id,tipo) VALUES
	 (11,'PODAS'),
	 (12,'RETIRO DE RAMAS Y PASTOS'),
	 (13,'BARRIDO DE CALLES'),
	 (14,'ARREGLO DE VEREDA (AGUA)'),
	 (15,'ARREGLO DE CALLES'),
	 (16,'REGADOR'),
	 (17,'MANEJO INTEGRADO DE PLAGAS'),
	 (18,'RETIRO DE VEHICULOS'),
	 (19,'VEHICULO MAL ESTACIONADO'),
	 (20,'LUMINARIAS');
INSERT INTO eolida.tipo_reclamo (id,tipo) VALUES
	 (21,'CUIDADO RESPONSABLE DE ANIMALES'),
	 (22,'SEMAFORO'),
	 (23,'RETIRO DE TIERRA'),
	 (24,'CARTELERIA Y SEÑALIZACION'),
	 (25,'RETIRO DE ESCOMBROS'),
	 (26,'RUIDOS MOLESTOS'),
	 (27,'LIMPIEZA DE CANAL O REJILLA'),
	 (28,'ARREGLO DE VEREDA (CLOACAS)'),
	 (29,'REPARACION DE VEREDA'),
	 (30,'ADMINISTRATIVO');
INSERT INTO eolida.tipo_reclamo (id,tipo) VALUES
	 (31,'DAÑOS EN ESPACIOS PUBLICOS'),
	 (32,'INTERVENCION DE G.U.M.'),
	 (33,'JUZGADO DE FALTAS'),
	 (34,'TENENCIA DE CABALLO'),
	 (35,'CALLE EN MAL ESTADO'),
	 (36,'CHATARRAS, BASURA, MICROBASURAL');
