package muni.eolida.sisifo.model.enums;

public enum TipoDocumentoEnum {
    TIPO_DOCUMENTO_DNI,
    TIPO_DOCUMENTO_EXTRANJERO,
    TIPO_DOCUMENTO_LIBRETA_CIVICA,
    TIPO_DOCUMENTO_LIBRETA_ENROLAMIENTO,
    TIPO_DOCUMENTO_PASAPORTE
}
